unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# enables vi keys e.g. for copy mode navigation
setw -g mode-keys vi
# y for yank instead of enter
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'

set -g base-index 1
setw -g pane-base-index 1
# this renumbers windows like if you close window 2, window 3 becomes the new window 2
set -g renumber-windows on
set-option -g status-position top
set-option -g history-limit 30000
# to be able to use mouse e.g. to scroll, click into panes, resize panes
set-option -g mouse on
# Styling
set-option -g status-style bg=#2D2F32
set -g status-right ""
# set color for active window
set-window-option -g window-status-current-style fg=red
# Remove the asterisk (*) from the active window
set-window-option -g window-status-current-format " #I #W "
# Remove the dash (-) from inactive windows
set-window-option -g window-status-format " #I #W "
# Set the color of inactive pane borders
set -g pane-border-style "fg=blue"

# Set the color of the active pane border
set -g pane-active-border-style "fg=blue"

# Shortcut to source the tmux conf file
bind r source-file ~/.tmux.conf \; display "Sourced .tmux.conf"
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"
# new window will open with current path
bind c new-window -c "#{pane_current_path}"
# switch easily between previous window
bind Space last-window
# switch between previous session
bind-key C-Space switch-client -l
# vim like movement between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# center the window overview
set -g status-justify left
# set refresh rate of the status bar (default 15), not too small!!!
set -g status-interval 10
# vim-style resizing of an active pane with prefix key because without Ctrl+L would interfere with clean
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

# Run a specific command when attaching or creating a new session
# the following 3 are classic hook configs
#set-hook -g session-created 'send-keys "fastfetch" Enter'
#set-hook -g client-attached 'send-keys "fastfetch" Enter'
#set-hook -g window-linked 'send-keys "fastfetch" Enter'

# execute fastfetch command when creating new session
set-hook -g session-created 'run-shell "tmux send-keys fastfetch Enter"'
# executing fastfetch command when creating/linking new window in a session
# if same command as above would be used, fastfetch would be executed twice on the first window
# since index starts at 1 in this setup, only execute this for windows > 1
set-hook -g window-linked 'run-shell "if [ #{window_index} -gt 1 ]; then tmux send-keys fastfetch Enter; fi"'

# plugins
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
